[package]
name = "pig_latinizator"
version = "0.1.0"
authors = ["PhobicRemnant <sergio.m.gonzalez.a.94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
